services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"  # ASP.NET backend
      - "4200:4200"  # Angular frontend
    volumes:
      - .:/app
      - /app/ClientApp/node_modules  # Evita conflictos de permisos
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    working_dir: /app
    stdin_open: true
    tty: true