name: Build and deploy ASP.Net Core app to Azure Web App - radar7-staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./Radar7D.csproj

      - name: Build project
        run: dotnet build ./Radar7D.csproj --configuration Release --no-restore

      - name: Clean build output
        run: |
          rm -rf ./bin
          rm -rf ./obj
          rm -rf ./publish
          
      - name: Publish project
        run: dotnet publish ./Radar7D.csproj --configuration Release --output ./publish
      
      - name: Clean extra files before packaging
        run: |
          find ./publish -name "*.runtimeconfig.json" ! -name "Radar7D.runtimeconfig.json" -delete

      - name: Zip published output
        run: zip -r deploy-package.zip ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy-package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3646BA811BC540728359111478F32019 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_71BE38D6C4AA441FB8C96F1EAAC857D8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CBC6487AA2244E27BEB9D25DBBE9ED32 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'radar7-staging'
          slot-name: 'Production'
          package: deploy-package.zip